version: '3.9'

services:
  db:
    image: postgres:16
    container_name: bot-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: bot-bot
    command: python run.py
    env_file:
      - .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - TOKEN=${TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
